// Auto-generated by scripts/generate-asset-manifest.js
export const AUTO_ASSET_MANIFEST = {
  "0": {
    "folderName": "Fieldlands Trail",
    "ordinary": [],
    "alpha": null,
    "alphaVariants": [],
    "legendary": []
  },
  "1": {
    "folderName": "Sandglass Flats",
    "ordinary": [],
    "alpha": null,
    "alphaVariants": [],
    "legendary": []
  },
  "2": {
    "folderName": "Frostpine Pass",
    "ordinary": [],
    "alpha": null,
    "alphaVariants": [],
    "legendary": []
  },
  "3": {
    "folderName": "Coastal Run",
    "ordinary": [],
    "alpha": null,
    "alphaVariants": [],
    "legendary": []
  },
  "4": {
    "folderName": "Crimson Mire",
    "ordinary": [],
    "alpha": null,
    "alphaVariants": [],
    "legendary": []
  },
  "5": {
    "folderName": "Coronet Approach",
    "ordinary": [],
    "alpha": null,
    "alphaVariants": [],
    "legendary": []
  },
  "6": {
    "folderName": "Fantasy World",
    "ordinary": [],
    "alpha": null,
    "alphaVariants": [],
    "legendary": []
  },
  "7": {
    "folderName": "Village World",
    "ordinary": [],
    "alpha": null,
    "alphaVariants": [],
    "legendary": []
  }
};
