// This file is auto-generated by scripts/generateAssetManifest.js.
// Add GLB files under public/assets/<Biome>/ordinary, alpha, or legendary, then rerun npm scripts.
export const AUTO_ASSET_MANIFEST = {
  "0": {
    "ordinary": [
      {
        "file": "ordinary/bellsprout.glb",
        "name": "bellsprout",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.35
      },
      {
        "file": "ordinary/bulbasaur.glb",
        "name": "bulbasaur",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.35
      },
      {
        "file": "ordinary/cacnea.glb",
        "name": "cacnea",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.35
      },
      {
        "file": "ordinary/oddish.glb",
        "name": "oddish",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.35
      },
      {
        "file": "ordinary/skiddo.glb",
        "name": "skiddo",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.35
      }
    ],
    "alpha": {
      "file": "alpha/venusaur.glb",
      "name": "venusaur",
      "rotation": [
        0,
        1.5707963267948966,
        0
      ],
      "scale": 0.35
    },
    "alphaVariants": [
      {
        "file": "alpha/venusaur.glb",
        "name": "venusaur",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.35
      }
    ],
    "legendary": [
      {
        "file": "legendary/virizion.glb",
        "name": "virizion",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 1
      }
    ]
  },
  "1": {
    "ordinary": [
      {
        "file": "ordinary/gible.glb",
        "name": "gible",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      },
      {
        "file": "ordinary/sandaconda.glb",
        "name": "sandaconda",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      },
      {
        "file": "ordinary/sandile.glb",
        "name": "sandile",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      },
      {
        "file": "ordinary/sandshrew.glb",
        "name": "sandshrew",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      },
      {
        "file": "ordinary/trapinch.glb",
        "name": "trapinch",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      }
    ],
    "alpha": {
      "file": "alpha/garchomp.glb",
      "name": "garchomp",
      "rotation": [
        0,
        1.5707963267948966,
        0
      ],
      "scale": 0.45
    },
    "alphaVariants": [
      {
        "file": "alpha/garchomp.glb",
        "name": "garchomp",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      }
    ],
    "legendary": [
      {
        "file": "legendary/landorus.glb",
        "name": "landorus",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 1
      },
      {
        "file": "legendary/regirock.glb",
        "name": "regirock",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 1
      }
    ]
  },
  "2": {
    "ordinary": [
      {
        "file": "ordinary/houndour.glb",
        "name": "houndour",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      },
      {
        "file": "ordinary/magby.glb",
        "name": "magby",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      },
      {
        "file": "ordinary/numel.glb",
        "name": "numel",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      },
      {
        "file": "ordinary/slugma.glb",
        "name": "slugma",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      },
      {
        "file": "ordinary/tepig.glb",
        "name": "tepig",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      }
    ],
    "alpha": {
      "file": "alpha/camerupt.glb",
      "name": "camerupt",
      "rotation": [
        0,
        1.5707963267948966,
        0
      ],
      "scale": 0.45
    },
    "alphaVariants": [
      {
        "file": "alpha/camerupt.glb",
        "name": "camerupt",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      }
    ],
    "legendary": [
      {
        "file": "legendary/primal_groudon.glb",
        "name": "primal_groudon",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 1
      }
    ]
  },
  "3": {
    "ordinary": [
      {
        "file": "ordinary/cleffa.glb",
        "name": "cleffa",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      },
      {
        "file": "ordinary/igglybuff.glb",
        "name": "igglybuff",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      },
      {
        "file": "ordinary/morelull.glb",
        "name": "morelull",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      },
      {
        "file": "ordinary/munna.glb",
        "name": "munna",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      },
      {
        "file": "ordinary/zorua.glb",
        "name": "zorua",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      }
    ],
    "alpha": {
      "file": "alpha/absol.glb",
      "name": "absol",
      "rotation": [
        0,
        1.5707963267948966,
        0
      ],
      "scale": 0.45
    },
    "alphaVariants": [
      {
        "file": "alpha/absol.glb",
        "name": "absol",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      }
    ],
    "legendary": [
      {
        "file": "legendary/cresselia.glb",
        "name": "cresselia",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 1
      },
      {
        "file": "legendary/darkrai.glb",
        "name": "darkrai",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 1
      }
    ]
  },
  "4": {
    "ordinary": [
      {
        "file": "ordinary/drilbur.glb",
        "name": "drilbur",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      },
      {
        "file": "ordinary/geodude.glb",
        "name": "geodude",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      },
      {
        "file": "ordinary/joltik.glb",
        "name": "joltik",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      },
      {
        "file": "ordinary/roggenrola.glb",
        "name": "roggenrola",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      },
      {
        "file": "ordinary/tynamo.glb",
        "name": "tynamo",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      }
    ],
    "alpha": {
      "file": "alpha/eelektross.glb",
      "name": "eelektross",
      "rotation": [
        0,
        1.5707963267948966,
        0
      ],
      "scale": 0.45
    },
    "alphaVariants": [
      {
        "file": "alpha/eelektross.glb",
        "name": "eelektross",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      }
    ],
    "legendary": [
      {
        "file": "legendary/regieleki.glb",
        "name": "regieleki",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 1
      }
    ]
  },
  "5": {
    "ordinary": [
      {
        "file": "ordinary/snom.glb",
        "name": "snom",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      },
      {
        "file": "ordinary/snorunt.glb",
        "name": "snorunt",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      },
      {
        "file": "ordinary/snover.glb",
        "name": "snover",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      },
      {
        "file": "ordinary/vanillite.glb",
        "name": "vanillite",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      },
      {
        "file": "ordinary/vulpix.glb",
        "name": "vulpix",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      }
    ],
    "alpha": {
      "file": "alpha/froslass.glb",
      "name": "froslass",
      "rotation": [
        0,
        1.5707963267948966,
        0
      ],
      "scale": 0.45
    },
    "alphaVariants": [
      {
        "file": "alpha/froslass.glb",
        "name": "froslass",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      },
      {
        "file": "alpha/glalie.glb",
        "name": "glalie",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      }
    ],
    "legendary": [
      {
        "file": "legendary/black_kyurem.glb",
        "name": "black_kyurem",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 1
      },
      {
        "file": "legendary/white_kyurem.glb",
        "name": "white_kyurem",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 1
      }
    ]
  },
  "6": {
    "ordinary": [
      {
        "file": "ordinary/cottonee.glb",
        "name": "cottonee",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.35
      },
      {
        "file": "ordinary/drifloon.glb",
        "name": "drifloon",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.35
      },
      {
        "file": "ordinary/hoppip.glb",
        "name": "hoppip",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.35
      },
      {
        "file": "ordinary/swablu.glb",
        "name": "swablu",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.35
      },
      {
        "file": "ordinary/togetic.glb",
        "name": "togetic",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.35
      }
    ],
    "alpha": {
      "file": "alpha/altaria.glb",
      "name": "altaria",
      "rotation": [
        0,
        1.5707963267948966,
        0
      ],
      "scale": 0.42
    },
    "alphaVariants": [
      {
        "file": "alpha/altaria.glb",
        "name": "altaria",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.42
      }
    ],
    "legendary": [
      {
        "file": "legendary/rayquaza.glb",
        "name": "rayquaza",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 1
      }
    ]
  },
  "7": {
    "ordinary": [
      {
        "file": "ordinary/elgyem.glb",
        "name": "elgyem",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.42
      },
      {
        "file": "ordinary/gastly.glb",
        "name": "gastly",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.42
      },
      {
        "file": "ordinary/minior.glb",
        "name": "minior",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.42
      },
      {
        "file": "ordinary/shedinja.glb",
        "name": "shedinja",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.42
      },
      {
        "file": "ordinary/sigilyph.glb",
        "name": "sigilyph",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.42
      }
    ],
    "alpha": {
      "file": "alpha/banette.glb",
      "name": "banette",
      "rotation": [
        0,
        1.5707963267948966,
        0
      ],
      "scale": 0.58
    },
    "alphaVariants": [
      {
        "file": "alpha/banette.glb",
        "name": "banette",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.58
      }
    ],
    "legendary": [
      {
        "file": "legendary/giratina.glb",
        "name": "giratina",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 1
      }
    ]
  }
};
