// This file is auto-generated by scripts/generateAssetManifest.js.
// Add GLB files under public/assets/<Biome>/ordinary, alpha, or legendary, then rerun npm scripts.
export const AUTO_ASSET_MANIFEST = {
  "0": {
    "ordinary": [
      {
        "file": "ordinary/creature_01.glb",
        "name": "creature_01",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.35
      }
    ],
    "alpha": {
      "file": "alpha/alpha_01.glb",
      "name": "alpha_01",
      "rotation": [
        0,
        1.5707963267948966,
        0
      ],
      "scale": 0.35
    },
    "alphaVariants": [
      {
        "file": "alpha/alpha_01.glb",
        "name": "alpha_01",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.35
      }
    ],
    "legendary": []
  },
  "1": {
    "ordinary": [
      {
        "file": "ordinary/creature_01.glb",
        "name": "creature_01",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      },
      {
        "file": "ordinary/creature_02.glb",
        "name": "creature_02",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      }
    ],
    "alpha": {
      "file": "alpha/alpha_01.glb",
      "name": "alpha_01",
      "rotation": [
        0,
        1.5707963267948966,
        0
      ],
      "scale": 0.45
    },
    "alphaVariants": [
      {
        "file": "alpha/alpha_01.glb",
        "name": "alpha_01",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      }
    ],
    "legendary": []
  },
  "2": {
    "ordinary": [
      {
        "file": "ordinary/creature_01.glb",
        "name": "creature_01",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      }
    ],
    "alpha": {
      "file": "alpha/alpha_01.glb",
      "name": "alpha_01",
      "rotation": [
        0,
        1.5707963267948966,
        0
      ],
      "scale": 0.45
    },
    "alphaVariants": [
      {
        "file": "alpha/alpha_01.glb",
        "name": "alpha_01",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      }
    ],
    "legendary": [
      {
        "file": "legendary/primal_groudon.glb",
        "name": "primal_groudon",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 1
      }
    ]
  },
  "3": {
    "ordinary": [
      {
        "file": "ordinary/creature_01.glb",
        "name": "creature_01",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      }
    ],
    "alpha": {
      "file": "alpha/alpha_01.glb",
      "name": "alpha_01",
      "rotation": [
        0,
        1.5707963267948966,
        0
      ],
      "scale": 0.45
    },
    "alphaVariants": [
      {
        "file": "alpha/alpha_01.glb",
        "name": "alpha_01",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      }
    ],
    "legendary": []
  },
  "4": {
    "ordinary": [
      {
        "file": "ordinary/creature_01.glb",
        "name": "creature_01",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      }
    ],
    "alpha": {
      "file": "alpha/alpha_01.glb",
      "name": "alpha_01",
      "rotation": [
        0,
        1.5707963267948966,
        0
      ],
      "scale": 0.45
    },
    "alphaVariants": [
      {
        "file": "alpha/alpha_01.glb",
        "name": "alpha_01",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      }
    ],
    "legendary": []
  },
  "5": {
    "ordinary": [
      {
        "file": "ordinary/creature_01.glb",
        "name": "creature_01",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      }
    ],
    "alpha": {
      "file": "alpha/alpha_01.glb",
      "name": "alpha_01",
      "rotation": [
        0,
        1.5707963267948966,
        0
      ],
      "scale": 0.45
    },
    "alphaVariants": [
      {
        "file": "alpha/alpha_01.glb",
        "name": "alpha_01",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.45
      }
    ],
    "legendary": [
      {
        "file": "legendary/black_kyurem.glb",
        "name": "black_kyurem",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 1
      },
      {
        "file": "legendary/white_kyurem.glb",
        "name": "white_kyurem",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 1
      }
    ]
  },
  "6": {
    "ordinary": [
      {
        "file": "ordinary/creature_01.glb",
        "name": "creature_01",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.35
      },
      {
        "file": "ordinary/creature_02.glb",
        "name": "creature_02",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.35
      }
    ],
    "alpha": {
      "file": "alpha/alpha_01.glb",
      "name": "alpha_01",
      "rotation": [
        0,
        1.5707963267948966,
        0
      ],
      "scale": 0.42
    },
    "alphaVariants": [
      {
        "file": "alpha/alpha_01.glb",
        "name": "alpha_01",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.42
      }
    ],
    "legendary": []
  },
  "7": {
    "ordinary": [
      {
        "file": "ordinary/creature_01.glb",
        "name": "creature_01",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.42
      }
    ],
    "alpha": {
      "file": "alpha/alpha_01.glb",
      "name": "alpha_01",
      "rotation": [
        0,
        1.5707963267948966,
        0
      ],
      "scale": 0.58
    },
    "alphaVariants": [
      {
        "file": "alpha/alpha_01.glb",
        "name": "alpha_01",
        "rotation": [
          0,
          1.5707963267948966,
          0
        ],
        "scale": 0.58
      }
    ],
    "legendary": []
  }
};
