const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const ASSETS_ROOT = path.join(ROOT, 'public', 'assets');
const OUTPUT_FILE = path.join(ROOT, 'src', 'world', 'generatedAssetManifest.js');

const BIOME_ASSET_FOLDERS = [
  'Grass Biome',
  'Desert Biome',
  'Volcanic Biome',
  'Moonlit Biome',
  'Cave Biome',
  'Icy Biome',
  'Sky Biome',
  'Distortion Realm',
];

const DEFAULTS_BY_BIOME = {
  0: { ordinary: { scale: 0.35 }, alpha: { scale: 0.35 }, legendary: { scale: 1 } },
  1: { ordinary: { scale: 0.45 }, alpha: { scale: 0.45 }, legendary: { scale: 1 } },
  2: { ordinary: { scale: 0.45 }, alpha: { scale: 0.45 }, legendary: { scale: 1 } },
  3: { ordinary: { scale: 0.45 }, alpha: { scale: 0.45 }, legendary: { scale: 1 } },
  4: { ordinary: { scale: 0.45 }, alpha: { scale: 0.45 }, legendary: { scale: 1 } },
  5: { ordinary: { scale: 0.45 }, alpha: { scale: 0.45 }, legendary: { scale: 1 } },
  6: { ordinary: { scale: 0.35 }, alpha: { scale: 0.42 }, legendary: { scale: 1 } },
  7: { ordinary: { scale: 0.42 }, alpha: { scale: 0.58 }, legendary: { scale: 1 } },
};

const DEFAULT_ROTATION = [0, Math.PI / 2, 0];

function readJson(filePath) {
  if (!fs.existsSync(filePath)) {
    return {};
  }

  try {
    return JSON.parse(fs.readFileSync(filePath, 'utf8'));
  } catch (error) {
    throw new Error(`Invalid asset metadata JSON at ${filePath}: ${error.message}`);
  }
}

function getGlbFiles(directory) {
  if (!fs.existsSync(directory)) {
    return [];
  }

  return fs.readdirSync(directory)
    .filter((fileName) => fileName.toLowerCase().endsWith('.glb'))
    .sort((a, b) => a.localeCompare(b));
}

function normalizeRotation(value) {
  return Array.isArray(value) && value.length === 3
    ? value.map((entry) => Number(entry) || 0)
    : DEFAULT_ROTATION;
}

function buildAssetEntry(folderName, type, fileName, biomeDefaults, metadata) {
  const relativeFile = `${type}/${fileName}`;
  const typeDefaults = biomeDefaults[type] || {};
  const fileMetadata = metadata.files?.[relativeFile] || metadata.files?.[fileName] || {};
  const typeMetadata = metadata.defaults?.[type] || {};
  const merged = {
    ...typeDefaults,
    ...typeMetadata,
    ...fileMetadata,
  };

  return {
    file: relativeFile,
    name: merged.name || path.basename(fileName, path.extname(fileName)),
    rotation: normalizeRotation(merged.rotation),
    scale: Number.isFinite(Number(merged.scale))
      ? Number(merged.scale)
      : Number(typeDefaults.scale || 0.45),
  };
}

function buildBiomeManifest(folderName, biomeId) {
  const biomePath = path.join(ASSETS_ROOT, folderName);
  const metadata = readJson(path.join(biomePath, 'assets.json'));
  const biomeDefaults = DEFAULTS_BY_BIOME[biomeId] || {};
  const ordinary = getGlbFiles(path.join(biomePath, 'ordinary')).map((fileName) =>
    buildAssetEntry(folderName, 'ordinary', fileName, biomeDefaults, metadata)
  );
  const alphaVariants = getGlbFiles(path.join(biomePath, 'alpha')).map((fileName) =>
    buildAssetEntry(folderName, 'alpha', fileName, biomeDefaults, metadata)
  );
  const legendary = getGlbFiles(path.join(biomePath, 'legendary')).map((fileName) =>
    buildAssetEntry(folderName, 'legendary', fileName, biomeDefaults, metadata)
  );

  return {
    ordinary,
    alpha: alphaVariants[0] || null,
    alphaVariants,
    legendary,
  };
}

function formatManifest(manifest) {
  return `// This file is auto-generated by scripts/generateAssetManifest.js.\n`
    + `// Add GLB files under public/assets/<Biome>/ordinary, alpha, or legendary, then rerun npm scripts.\n`
    + `export const AUTO_ASSET_MANIFEST = ${JSON.stringify(manifest, null, 2)};\n`;
}

function main() {
  const manifest = BIOME_ASSET_FOLDERS.reduce((result, folderName, biomeId) => {
    result[biomeId] = buildBiomeManifest(folderName, biomeId);
    return result;
  }, {});

  fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
  fs.writeFileSync(OUTPUT_FILE, formatManifest(manifest));
  console.log(`Generated ${path.relative(ROOT, OUTPUT_FILE)}`);
}

main();
